import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
// tl-16's REGRESSION GATE, and the one test in this spec that could not be written from
// inside the spec.
//
// Every other test here asserts something about the template layer. This one asserts that
// the layer changed nothing: it renders both participant documents, the digest, the
// report, the three AI instruction blocks and the empty-state variants of each, from fixed
// inputs, and compares the whole 22kB against a fixture GENERATED BY RUNNING THIS SAME
// FILE ON `main`. The fixture is therefore evidence rather than a snapshot of my own
// output — a self-generated snapshot would have passed just as happily over a build that
// had quietly reworded every email in the app.
//
// If this fails after a deliberate wording change to a shipped default, regenerate the
// fixture from the commit BEFORE that change and say in the commit message what moved. Do
// not regenerate it from the build under test; that is the one thing it exists to stop.
import { buildAllReports } from '../src/reports/build'
import { renderParticipantEmailMarkdown } from '../src/reports/participantEmail'
import { renderEventDigestMarkdown } from '../src/reports/eventDigest'
import { renderParticipantReportMarkdown } from '../src/reports/markdown'
import { annotateObservations, participantGate } from '../src/reports/verification'
import { activityAnalytics, buildCaptureIndex, situate } from '../src/reports/analytics'
import { renderRoutingDoc } from '../src/ai/workspace'
import { buildScenarioPrompt } from '../src/ai/scenarioDraft'
import { buildGuidancePrompt } from '../src/ai/guidancePrompt'
import { GENERAL_INSTRUCTIONS } from '../src/ai/brief'
import { DEFAULT_SCALE } from '../src/lib/scale'
import { activity, evaluation, ksa, obs, participant, team, verdict } from './factories'
import type { MentoringConversation, ObservationRecord } from '../src/lib/types'

const ksas = [ksa('GENRE', { goal_title: 'Genre Theory' }), ksa('CHECK', { goal_title: 'Checking' })]
const people = [participant({ id: 'p-0', name: 'Amos Khokhar' }), participant({ id: 'p-1', name: 'Ruth Verghese' })]
const teams = [team()]
const act = activity({ id: 'act-1', title: 'Psalm 1 workshop', day: '2026-08-26' })
const cap = evaluation({ client_id: 'cap-1', activity_id: 'act-1', evaluator_email: 'josh@sil.org' })

const observations: ObservationRecord[] = [
  obs({ id: 'o-1', capture_client_id: 'cap-1', participant_id: 'p-0', participant_name: 'Amos Khokhar', ksa_code: 'GENRE', evidence_designation: 3, text: 'named the genre and defended it', source_excerpt: 'he named the genre' }),
  obs({ id: 'o-2', capture_client_id: 'cap-1', participant_id: 'p-0', participant_name: 'Amos Khokhar', ksa_code: 'CHECK', evidence_designation: 1, text: 'skipped the community check', source_excerpt: 'went straight on' }),
  obs({ id: 'o-3', capture_client_id: 'cap-1', participant_id: 'p-1', participant_name: 'Ruth Verghese', ksa_code: 'GENRE', evidence_designation: 1, text: 'read it as prose', source_excerpt: 'as prose' }),
  obs({ id: 'o-4', capture_client_id: 'cap-1', participant_id: 'p-1', participant_name: 'Ruth Verghese', ksa_code: 'CHECK', evidence_designation: 2, needs_review: true, confidence: 'low', text: 'partly checked', source_excerpt: 'partly' }),
]
const verdicts = [verdict({ observation_id: 'o-1', evaluator_email: 'a@sil.org' })]
const conversations: MentoringConversation[] = []

const annotated = annotateObservations(observations, verdicts)
const reports = buildAllReports(people, ksas, annotated, teams)
const situated = situate(annotated, buildCaptureIndex([cap]))
const analytics = activityAnalytics(act, ksas, situated, [cap])

const out: string[] = []
const section = (title: string, body: string) => out.push(`\n===== ${title} =====\n${body}`)

for (const r of reports) {
  const gate = participantGate(annotated.filter((o) => o.participant_id === r.participant_id))
  section(`participant email ${r.participant_id}`, renderParticipantEmailMarkdown(r, gate, 'Psalms Workshop', '2026-08-26', { fromName: 'Josh' }))
  section(`participant email ${r.participant_id} no-from`, renderParticipantEmailMarkdown(r, undefined, 'Psalms Workshop', '2026-08-26'))
  section(`participant report ${r.participant_id}`, renderParticipantReportMarkdown(r, 'Psalms Workshop', '2026-08-26', gate))
  section(`participant report ${r.participant_id} no-gate`, renderParticipantReportMarkdown(r, 'Psalms Workshop', '2026-08-26'))
}
/**
 * THREE RENDERINGS THE FIRST VERSION OF THIS FIXTURE NEVER TOOK, found by the second-AI
 * review counting occurrences in the file rather than trusting the header.
 *
 * `event_digest.no-pattern` needs a cohort where nobody scored low; both gate sentences in
 * `participant_report` need a gate that CLEARS, which needs enough confirmations; and the
 * `disputed` half of the locked gate's `extra` fragment needs a rejecting verdict. An
 * uncovered default is exactly where a silent rewording would hide, and the header claimed
 * to render "the empty-state variants of each".
 */
const clean = [
  obs({ id: 'oc-1', capture_client_id: 'cap-1', participant_id: 'p-0', participant_name: 'Amos Khokhar', ksa_code: 'GENRE', evidence_designation: 3, text: 'clean', source_excerpt: 'clean' }),
  obs({ id: 'oc-2', capture_client_id: 'cap-1', participant_id: 'p-1', participant_name: 'Ruth Verghese', ksa_code: 'GENRE', evidence_designation: 3, text: 'clean too', source_excerpt: 'clean too' }),
]
section(
  'event digest no pattern',
  renderEventDigestMarkdown(
    activityAnalytics(act, ksas, situate(annotateObservations(clean, []), buildCaptureIndex([cap])), [cap]),
    [],
    { fromName: 'Josh' },
  ),
)

const verifiedObs = [obs({ id: 'ov-1', capture_client_id: 'cap-1', participant_id: 'p-0', participant_name: 'Amos Khokhar', ksa_code: 'GENRE', evidence_designation: 3, text: 'seen twice', source_excerpt: 'seen twice' })]
const twoConfirms = [
  verdict({ observation_id: 'ov-1', evaluator_email: 'a@sil.org' }),
  verdict({ observation_id: 'ov-1', evaluator_email: 'b@sil.org' }),
]
const verifiedAnnotated = annotateObservations(verifiedObs, twoConfirms)
const verifiedReport = buildAllReports([people[0]], ksas, verifiedAnnotated, teams)[0]
section(
  'participant report gate ready',
  renderParticipantReportMarkdown(verifiedReport, 'Psalms Workshop', '2026-08-26', participantGate(verifiedAnnotated)),
)

const disputedAnnotated = annotateObservations(verifiedObs, [
  verdict({ observation_id: 'ov-1', evaluator_email: 'a@sil.org' }),
  verdict({ observation_id: 'ov-1', evaluator_email: 'b@sil.org', decision: 'reject' }),
])
section(
  'participant report gate disputed',
  renderParticipantReportMarkdown(
    buildAllReports([people[0]], ksas, disputedAnnotated, teams)[0],
    'Psalms Workshop',
    '2026-08-26',
    participantGate(disputedAnnotated),
  ),
)

const empty = buildAllReports([participant({ id: 'p-9', name: 'Nobody Observed' })], ksas, [], teams)[0]
section('participant email empty', renderParticipantEmailMarkdown(empty, undefined, 'Psalms Workshop', '2026-08-26', { fromName: 'Josh' }))
section('participant report empty', renderParticipantReportMarkdown(empty, 'Psalms Workshop', '2026-08-26'))
section('event digest', renderEventDigestMarkdown(analytics, conversations, { fromName: 'Josh', toName: 'facilitators' }))
section('event digest bare', renderEventDigestMarkdown(analytics, conversations))
section('event digest empty', renderEventDigestMarkdown(activityAnalytics(act, ksas, [], [cap]), []))
section('routing doc', renderRoutingDoc(DEFAULT_SCALE))
section('scenario prompt', buildScenarioPrompt('<doc>'))
section('guidance prompt', buildGuidancePrompt('<evidence>'))
section('general instructions', GENERAL_INSTRUCTIONS)

describe('a workshop that has authored nothing gets exactly the pre-tl-16 output', () => {
  it('matches the fixture rendered from main, byte for byte', () => {
    const fixture = readFileSync(
      path.join(__dirname, 'fixtures', 'tl16-default-output.txt'),
      'utf8',
    )
    expect(out.join('\n')).toBe(fixture)
  })
})
